# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

env:
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
  MONGODB_URI: ${{ secrets.MONGODB_URI }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}

on:
  push:
    branches-ignore: ["beta", "version-1.0"]
  pull_request:
    branches-ignore: ["beta", "version-1.0"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "22"

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Node.js dependencies
      run: |
        if [ -f package.json ]; then npm install; fi

    - name: Build Tailwind CSS
      run: |
        if [ -f src/frontend/css/tailwindcss.css ]; then npm run build; fi

    - name: Run tests with pytest
      run: |
        pytest src/tests